apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-llm
  labels:
    app: agent-morpheus
    component: nim-llm
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: nim-llm
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: nim-llm
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.driver: "true"
      imagePullSecrets: []
      tolerations:
        - key: p4-gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nim-llm
          image: nvcr.io/nim/meta/llama-3.1-8b-instruct:1.3
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          resources:
            limits:
              memory: "16Gi"
              cpu: "500m"
              nvidia.com/gpu: "1"
            requests:
              memory: "8Gi"
              cpu: "100m"
              nvidia.com/gpu: "1"
          env:
            - name: NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ngc_api_key
                  name: agent-morpheus-secret
          volumeMounts:
            - name: cache
              mountPath: /opt/nim/.cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: nim-llm-cache
---
apiVersion: v1
kind: Service
metadata:
  name: nim-llm
  labels:
    app: agent-morpheus
    component: nim-llm
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: agent-morpheus
    component: nim-llm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-llm-cache
  labels:
    app: agent-morpheus
    component: nim-llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi