apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-embed
  labels:
    app: agent-morpheus
    component: nim-embed
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: nim-embed
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: nim-embed
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.driver: "true"
      imagePullSecrets: []
      tolerations:
        - key: p4-gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: nim-embed
          image: nvcr.io/nim/nvidia/nv-embedqa-e5-v5:1
          ports:
            - name: http
              protocol: TCP
              containerPort: 8000
          resources:
            limits:
              memory: "16Gi"
              cpu: "500m"
              nvidia.com/gpu: "1"
            requests:
              memory: "8Gi"
              cpu: "100m"
              nvidia.com/gpu: "1"
          env:
            - name: NGC_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ngc_api_key
                  name: agent-morpheus-secret
          volumeMounts:
            - name: cache
              mountPath: /opt/nim/.cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: nim-embed-cache
---
apiVersion: v1
kind: Service
metadata:
  name: nim-embed
  labels:
    app: agent-morpheus
    component: nim-embed
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: agent-morpheus
    component: nim-embed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nim-embed-cache
  labels:
    app: agent-morpheus
    component: nim-embed
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi