apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
  name: allow-from-agent-morpheus-namespaces
  namespace: morpheus-cn-models-nim
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          application: agent-morpheus
  podSelector: {}
  policyTypes:
  - Ingress

