apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../local-llama3.1-70b-4bit/

secretGenerator:
  - name: langsmith-secret
    envs:
      - langsmith-secret.env

patchesStrategicMerge:
  - |- 
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: agent-morpheus-rh
      labels:
        app: agent-morpheus
        component: agent-morpheus-rh
    spec:
      selector:
        matchLabels:
          app: agent-morpheus
          component: agent-morpheus-rh
      template:
        metadata:
          labels:
            app: agent-morpheus
            component: agent-morpheus-rh
        spec:
          containers:
            - name: agent-morpheus
              image: quay.io/ecosystem-appeng/agent-morpheus-rh:latest
              imagePullPolicy: Always
              workingDir: /workspace/
              env:
              - name: AGENT_MORPHEUS_PYTHON_COMMAND
                value: "python /workspace/src/main.py --log_level DEBUG cve pipeline --config_file /configs/agent-morpheus-config.json" 
              - name: LANGCHAIN_TRACING_V2 
                value: "true"
              - name: LANGCHAIN_ENDPOINT 
                value: https://api.smith.langchain.com
                  
              - name: LANGCHAIN_API_KEY 
                valueFrom:
                  secretKeyRef:
                    name: langsmith-secret
                    key: langchainApiKey   
                
              args:
                - "sleep"
                - "infinity"
                

configMapGenerator:
  - behavior: replace

    name: nginx-cache-routes
    files:
      - nginx/templates/routes/nemo.conf.template
      - nginx/templates/routes/nim.conf.template
      - nginx/templates/routes/nvidia.conf.template
      - nginx/templates/routes/openai.conf.template
