apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cache
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: NGINX_UPSTREAM_NIM_LLM
              value: https://integrate.api.nvidia.com
            - name: NGINX_UPSTREAM_NIM_EMBED
              value: https://integrate.api.nvidia.com
            - name: NGINX_UPSTREAM_OPENAI
              value: https://integrate.api.nvidia.com
