apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-rh
  labels:
    app: agent-morpheus
    component: agent-morpheus-rh
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: agent-morpheus-rh
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: agent-morpheus-rh
    spec:
      containers:
        - name: agent-morpheus
          env:

            - name: OPENAI_BASE_URL
              value: http://llama3-8b-instruct-1xgpu-predictor-00001-private.morpheus-cn-models-nim/v1

            - name: OPENAI_API_KEY
              value: dummy-string

