apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-rh
  labels:
    app: agent-morpheus
    component: agent-morpheus-rh
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: agent-morpheus-rh
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: agent-morpheus-rh
    spec:
      containers:
        - name: agent-morpheus
          env:
            - name: NVIDIA_API_KEY
              valueFrom:
                secretKeyRef:
                  key: nvidia_api_key
                  name: agent-morpheus-secret