apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cache
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: NGINX_UPSTREAM_NIM_LLM
              value: http://llama3-1-70b-instruct-4bit.agent-morpheus-models.svc.cluster.local:8000
            - name: NGINX_UPSTREAM_OPENAI
              value: http://llama3-1-70b-instruct-4bit.agent-morpheus-models.svc.cluster.local:8000
