apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus
    component: agent-morpheus-client
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: agent-morpheus-client
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: agent-morpheus-client
    spec:
      imagePullSecrets: []
      containers:
        - name: agent-morpheus-client
          image: quay.io/ecosystem-appeng/agent-morpheus-client:latest
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          env:
            - name: QUARKUS_REST-CLIENT_MORPHEUS_URL
              value: http://nginx-cache:8080/scan
            - name: QUARKUS_MONGODB_HOSTS
              value: agent-morpheus-client-db:27017
            - name: QUARKUS_MONGODB_DATABASE
              value: agent-morpheus-client
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-client
  labels:
    app: agent-morpheus
    component: agent-morpheus-client
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agent-morpheus
    component: agent-morpheus-client
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: agent-morpheus-client
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: 8080
  to:
    kind: Service
    name: agent-morpheus-client
