apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-rh
  labels:
    app: agent-morpheus
    component: agent-morpheus-rh
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: agent-morpheus-rh
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: agent-morpheus-rh
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.driver: "true"
      imagePullSecrets: []
      tolerations:
        - key: p4-gpu
          operator: Exists
          effect: NoSchedule
      serviceAccountName: morpheus-sa
      containers:
        - name: agent-morpheus
          image: quay.io/ecosystem-appeng/agent-morpheus-rh:latest
          imagePullPolicy: Always
          workingDir: /workspace/
          args:
            - "python"
            - "/workspace/src/main.py"
            - "--log_level"
            - "DEBUG"
            - "cve"
            - "pipeline"
            - "--config_file"
            - "/configs/agent-morpheus-config.json"
          securityContext:
            runAsUser: 0
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
          resources:
            limits:
              memory: "8Gi"
              cpu: "500m"
              nvidia.com/gpu: "1"
            requests:
              memory: "1Gi"
              cpu: "100m"
              nvidia.com/gpu: "1"
          env:
            - name: SERPAPI_API_KEY
              value: AGENT_MORPHEUS
            - name: NVD_API_KEY
              value: AGENT_MORPHEUS
            - name: NVIDIA_API_KEY
              value: AGENT_MORPHEUS
            - name: GHSA_API_KEY
              value: AGENT_MORPHEUS
            - name: OPENAI_API_KEY
              value: AGENT_MORPHEUS
            - name: NGC_API_KEY
              value: AGENT_MORPHEUS
            - name: CVE_DETAILS_BASE_URL
              value: http://nginx-cache:8080/cve-details
            - name: CWE_DETAILS_BASE_URL
              value: http://nginx-cache:8080/cwe-details
            - name: DEPSDEV_BASE_URL
              value: http://nginx-cache:8080/depsdev
            - name: FIRST_BASE_URL
              value: http://nginx-cache:8080/first
            - name: GHSA_BASE_URL
              value: http://nginx-cache:8080/ghsa
            - name: NGC_API_BASE
              value: http://nginx-cache:8080/nemo/v1
            - name: NIM_EMBED_BASE_URL
              value: http://nginx-cache:8080/nim_embed/v1
            - name: NVD_BASE_URL
              value: http://nginx-cache:8080/nvd
            - name: NVIDIA_API_BASE
              value: http://nginx-cache:8080/nim_llm/v1
            - name: OPENAI_API_BASE
              value: http://nginx-cache:8080/openai/v1
            - name: OPENAI_BASE_URL
              value: http://nginx-cache:8080/openai/v1
            - name: RHSA_BASE_URL
              value: http://nginx-cache:8080/rhsa
            - name: SERPAPI_BASE_URL
              value: http://nginx-cache:8080/serpapi
            - name: UBUNTU_BASE_URL
              value: http://nginx-cache:8080/ubuntu
            - name: ENABLE_EXTENDED_JS_PARSERS
              value: "True"
          volumeMounts:
            - name: config
              mountPath: /configs
            - name: cache
              mountPath: /morpheus-data
      volumes:
        - name: config
          configMap:
            name: agent-morpheus-config
        - name: cache
          persistentVolumeClaim:
            claimName: agent-morpheus-rh-data
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-rh
  labels:
    app: agent-morpheus
    component: agent-morpheus-rh
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: agent-morpheus
    component: agent-morpheus-rh
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-morpheus-rh-data
  labels:
    purpose: persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi