apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-morpheus-client-db
  labels:
    app: agent-morpheus
    component: agent-morpheus-client-db
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: agent-morpheus
      component: agent-morpheus-client-db
  template:
    metadata:
      labels:
        app: agent-morpheus
        component: agent-morpheus-client-db
    spec:
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:8.0.3-ubi8
          imagePullPolicy: IfNotPresent
          ports:
            - name: db
              protocol: TCP
              containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: agent-morpheus-client-data
---
apiVersion: v1
kind: Service
metadata:
  name: agent-morpheus-client-db
  labels:
    app: agent-morpheus
    component: agent-morpheus-client-db
spec:
  ports:
  - name: db
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: agent-morpheus
    component: agent-morpheus-client-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-morpheus-client-data
  labels:
    purpose: persistent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
