apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - anyuid-scc-permission.yaml
  - agent_morpheus-RH.yaml
  - agent_morpheus_client.yaml

generatorOptions:
  disableNameSuffixHash: false

secretGenerator:
  - name: agent-morpheus-secret
    envs:
      - secrets.env

patches:
  - path: ips-patch.json
              
    target:
      name: agent-morpheus-rh
      kind: Deployment

  - path: ips-patch-client.json

    target:
      name: agent-morpheus-client
      kind: Deployment

images:
  - name: quay.io/ecosystem-appeng/agent-morpheus-rh
    newTag: latest

  - name: quay.io/ecosystem-appeng/agent-morpheus-client
    newTag: latest
