apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-account.yaml
  - anyuid-scc-permission.yaml
  - nginx.yaml
  - agent_morpheus-RH.yaml
  - agent_morpheus_client_db.yaml
  - agent_morpheus_client.yaml

generatorOptions:
  disableNameSuffixHash: false

secretGenerator:
  - name: agent-morpheus-secret
    envs:
      - secrets.env

configMapGenerator:
  - name: nginx-cache-config
    files:
      - nginx.conf=nginx/nginx_cache.conf
  - name: nginx-cache-variables
    files:
      - nginx/templates/variables/template-variables.conf.template
  - name: nginx-cache-routes
    files:
      - nginx/templates/routes/intel.conf.template
      - nginx/templates/routes/nemo.conf.template
      - nginx/templates/routes/nim.conf.template
      - nginx/templates/routes/nvidia.conf.template
      - nginx/templates/routes/openai.conf.template
  - name: agent-morpheus-config
    files:
      - agent-morpheus-config.json

patches:
  - path: ips-patch.json
              
    target:
      name: agent-morpheus-rh
      kind: Deployment

  - path: ips-patch-client.json

    target:
      name: agent-morpheus-client
      kind: Deployment

images:
  - name: quay.io/ecosystem-appeng/agent-morpheus-rh
    newTag: latest

  - name: quay.io/ecosystem-appeng/agent-morpheus-client
    newTag: latest
